// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjqXCKgwbPRDiUTXJTm1QpsSmITpJeeI',
    appId: '1:702524155709:web:4e567e9224790fc6e18754',
    messagingSenderId: '702524155709',
    projectId: 'cookoo-record',
    authDomain: 'cookoo-record.firebaseapp.com',
    storageBucket: 'cookoo-record.firebasestorage.app',
    measurementId: 'G-7JZX8MRJS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHrLMtYBTyPiQrIJTmjQiDLC5YU5c_vk',
    appId: '1:702524155709:android:63309fc17769f7c9e18754',
    messagingSenderId: '702524155709',
    projectId: 'cookoo-record',
    storageBucket: 'cookoo-record.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71_ITUNtXBVhurmQ_0YL_O0PCk5USJpE',
    appId: '1:702524155709:ios:3a4704c5125f20d4e18754',
    messagingSenderId: '702524155709',
    projectId: 'cookoo-record',
    storageBucket: 'cookoo-record.firebasestorage.app',
    iosBundleId: 'com.example.cookooRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71_ITUNtXBVhurmQ_0YL_O0PCk5USJpE',
    appId: '1:702524155709:ios:3a4704c5125f20d4e18754',
    messagingSenderId: '702524155709',
    projectId: 'cookoo-record',
    storageBucket: 'cookoo-record.firebasestorage.app',
    iosBundleId: 'com.example.cookooRecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjqXCKgwbPRDiUTXJTm1QpsSmITpJeeI',
    appId: '1:702524155709:web:7f7e0b6b6f1e6a82e18754',
    messagingSenderId: '702524155709',
    projectId: 'cookoo-record',
    authDomain: 'cookoo-record.firebaseapp.com',
    storageBucket: 'cookoo-record.firebasestorage.app',
    measurementId: 'G-3CX8329KCC',
  );
}
